### ISSUE TITLE
default avatar generation not working via URL

### ISSUE THREAD

**Issue by simahawk** [4teamwork/ftw.avatar#7]
Plone 4.3.6 + ftw.avatar 1.0.6

If you never created/uploaded a portrait image and you access 
http://localhost:8080/Plone/portal_memberdata/portraits/user1

you get NOT FOUND.

If you go to 

http://localhost:8080/Plone/@@user-information?userid=user1

then the image is generated and if you go back to the image url it works.
I understand that this is because the /portraits traverse do not know anything about the avatar machinery, since it simply publish an object stored into it. And at first the img obj is not there yet.

A custom traverser on top of /portraits could solve it, or on top of portal_memberdata... I think a view would have precendence on the content itself, isn't it?

**Comment by jone** [comment]
In Plone default (without ftw.avatar), the portrait URL may also return a 404 NOT FOUND when accessed directly, so ftw.avatar has nothing to do with this behavior.
The idea is that whenever the portrait is used, ``getPersonalPortrait`` should be called for this member, which will either return the personal portrait or the default portrait.
This avoids the situation that a URL is generated which would respond with 404.

Since ftw.avatar is only changing ``getPersonalPortrait`` to not return the default portrait but generate a personal portait on the fly, it is still best practice to never generate the URL directly but always use ``getPersonalPortrait``.

Why do you get 404 errors? Are you generating the URL manually?

However, we could implement a safeguard for avoiding 404s.
I think registering the traverser on `/portraits` could be a little bit tricky, since `/portraits` is a simple `BTreeFolder2` which has no custom interfaces to detect exactly this folder, thus the traverser would be registered on any `BTreeFolder2` instance.
Registering the traverser on `portal_memberdata` would work, although it would be tricky to detect and handle missing images from there. We would have to implement something like a traversal lookahead.
A view would not work, I think, because the name would have to be the userid, which means that we would have to register a view per user :wink:

**Comment by simahawk** [comment]
Another solution would be: generating the image by calling `getPersonalPortrait` when the user is registered or better when the user logs in for the 1st time.
And this could be upon the integrator... we can just show how to to this in the README of the package ;-)
 What do you think?

**Comment by jone** [comment]
We often show the portrait in the personal menu:
<img width="267" alt="bildschirmfoto 2015-07-30 um 10 38 31" src="https://cloud.githubusercontent.com/assets/7469/8979003/315f0cd0-36a7-11e5-8274-5d0a448a3b04.png">
So we automatically have this effect, since the portrait is shown and thus generated on the very first page view of the user.

And yes, this could be generated upon first login by using event subscribers. The problem is that the registered- and login-events may not be fired when using an LDAP / AD or another authentication mechanism, which makes it a little bit harder.

I still not understand completely why this problem occurs. Which component is generating the URL to the portrait which does not exist? I still believe this cannot happen when using `getPersonalPortrait` consequently. :confused:

**Comment by simahawk** [comment]
Well, actually this is a non-problem if you act as you said: generate "sane urls" :)
The app I was using for testing this has not a safe behavior on this side, so I fixed it.
All my questions aimed at better understanding the whole machinery and if there could be ways to improve this stuff :)
So, I'm satisfied by your answers ;) Thanks a lot! Let's close this :)

**Comment by jone** [comment]
You're welcome, happy I could help :grinning:
